"""
cif2qe.py - Convert CIF files to Quantum ESPRESSO input format

Reads CIF files (from cutpos.py output) and generates Quantum ESPRESSO
.in input files for DFT calculations.
"""

import numpy as np
import sys
from ase.io import read


def write_qe_input(atoms, filename, pseudo_dir='./'):
    """
    Write Quantum ESPRESSO input file from ASE Atoms object.
    
    Args:
        atoms: ASE Atoms object
        filename: Output .in filename
        pseudo_dir: Directory containing pseudopotential files
    """
    symbols = atoms.get_chemical_symbols()
    unique_symbols = sorted(set(symbols))
    positions = atoms.get_positions()
    cell = atoms.get_cell()
    
    # Atomic masses (approximate)
    mass_map = {
        'C': 12.011, 'B': 10.81, 'N': 14.007,
        'Mo': 95.95, 'W': 183.84, 'S': 32.06,
        'Se': 78.971, 'Te': 127.60
    }
    
    with open(filename, 'w') as f:
        f.write("! Quantum ESPRESSO input file generated from CIF\n")
        f.write("! Generated by TwisterASEv2\n\n")
        
        # CONTROL namelist
        f.write("&CONTROL\n")
        base_name = filename.replace('.in', '')
        f.write(f"  calculation = 'scf'\n")
        f.write(f"  prefix = '{base_name}'\n")
        f.write(f"  pseudo_dir = '{pseudo_dir}'\n")
        f.write(f"  outdir = './tmp'\n")
        f.write(f"  verbosity = 'high'\n")
        f.write(f"  tprnfor = .true.\n")
        f.write(f"  tstress = .true.\n")
        f.write("/\n\n")
        
        # SYSTEM namelist
        f.write("&SYSTEM\n")
        f.write(f"  ibrav = 0\n")
        f.write(f"  nat = {len(atoms)}\n")
        f.write(f"  ntyp = {len(unique_symbols)}\n")
        f.write(f"  ecutwfc = 60.0\n")
        f.write(f"  ecutrho = 480.0\n")
        f.write(f"  occupations = 'smearing'\n")
        f.write(f"  smearing = 'gaussian'\n")
        f.write(f"  degauss = 0.01\n")
        f.write(f"  vdw_corr = 'DFT-D3'\n")
        f.write("/\n\n")
        
        # ELECTRONS namelist
        f.write("&ELECTRONS\n")
        f.write(f"  conv_thr = 1.0d-8\n")
        f.write(f"  mixing_beta = 0.3\n")
        f.write(f"  mixing_mode = 'plain'\n")
        f.write("/\n\n")
        
        # Atomic species
        f.write("ATOMIC_SPECIES\n")
        for sym in unique_symbols:
            mass = mass_map.get(sym, 1.0)
            f.write(f"  {sym}  {mass:.3f}  {sym}.upf\n")
        f.write("\n")
        
        # Cell parameters
        f.write("CELL_PARAMETERS angstrom\n")
        for vec in cell:
            f.write(f"  {vec[0]:16.10f}  {vec[1]:16.10f}  {vec[2]:16.10f}\n")
        f.write("\n")
        
        # Atomic positions
        f.write("ATOMIC_POSITIONS angstrom\n")
        for pos, sym in zip(positions, symbols):
            f.write(f"  {sym:3s}  {pos[0]:16.10f}  {pos[1]:16.10f}  {pos[2]:16.10f}\n")
        f.write("\n")
        
        # K-points
        f.write("K_POINTS automatic\n")
        f.write("  4 4 1  0 0 0\n")
        f.write("\n")


def main():
    """Main function to convert CIF to Quantum ESPRESSO format."""
    if len(sys.argv) < 2:
        print("Usage: python cif2qe.py <input.cif> [output.in]")
        print("\nExample:")
        print("  python cif2qe.py layer_1.cif layer_1.in")
        print("  python cif2qe.py relaxed_structure.cif structure.in")
        sys.exit(1)
    
    input_cif = sys.argv[1]
    
    if len(sys.argv) >= 3:
        output_in = sys.argv[2]
    else:
        output_in = input_cif.replace('.cif', '.in')
    
    print(f"\n{'='*60}")
    print("CIF to Quantum ESPRESSO Converter")
    print(f"{'='*60}\n")
    
    print(f"Reading: {input_cif}")
    try:
        atoms = read(input_cif)
        print(f"  Read {len(atoms)} atoms")
        print(f"  Elements: {sorted(set(atoms.get_chemical_symbols()))}")
    except Exception as e:
        print(f"[FAIL] Error reading CIF file: {e}")
        sys.exit(1)
    
    print(f"\nWriting: {output_in}")
    try:
        write_qe_input(atoms, output_in)
        print(f"  Quantum ESPRESSO input file written")
    except Exception as e:
        print(f"[FAIL] Error writing QE input file: {e}")
        sys.exit(1)
    
    print(f"\n{'='*60}")
    print("Conversion complete!")
    print(f"{'='*60}\n")
    print("Next steps:")
    print("  1. Obtain UPF pseudopotential files for each element")
    print("  2. Place them in pseudo_dir or update path in input file")
    print("  3. Run: pw.x < {output_in} > output.log")
    print()


if __name__ == '__main__':
    main()
