"""
cif2siesta.py - Convert CIF files to SIESTA input format

Reads CIF files (from cutpos.py output) and generates SIESTA .fdf input files
for DFT calculations.
"""

import numpy as np
import sys
from ase.io import read


def write_siesta_fdf(atoms, filename, pseudo_path='./'):
    """
    Write SIESTA .fdf input file from ASE Atoms object.
    
    Args:
        atoms: ASE Atoms object
        filename: Output .fdf filename
        pseudo_path: Path to pseudopotential files
    """
    symbols = atoms.get_chemical_symbols()
    unique_symbols = sorted(set(symbols))
    positions = atoms.get_positions()
    cell = atoms.get_cell()
    
    with open(filename, 'w') as f:
        f.write("# SIESTA input file generated from CIF\n")
        f.write("# Generated by TwisterASEv2\n\n")
        
        # System label
        base_name = filename.replace('.fdf', '')
        f.write(f"SystemName         {base_name}\n")
        f.write(f"SystemLabel        {base_name}\n\n")
        
        # Number of atoms and species
        f.write(f"NumberOfAtoms      {len(atoms)}\n")
        f.write(f"NumberOfSpecies    {len(unique_symbols)}\n\n")
        
        # Chemical species
        f.write("%block ChemicalSpeciesLabel\n")
        for i, sym in enumerate(unique_symbols, 1):
            atomic_number = atoms[symbols.index(sym)].number
            f.write(f"  {i}  {atomic_number}  {sym}\n")
        f.write("%endblock ChemicalSpeciesLabel\n\n")
        
        # Pseudopotentials
        f.write("# Pseudopotential paths\n")
        for sym in unique_symbols:
            f.write(f"# {sym}.psf should be in {pseudo_path}\n")
        f.write("\n")
        
        # Lattice vectors
        f.write("LatticeConstant    1.0 Ang\n")
        f.write("%block LatticeVectors\n")
        for vec in cell:
            f.write(f"  {vec[0]:16.10f}  {vec[1]:16.10f}  {vec[2]:16.10f}\n")
        f.write("%endblock LatticeVectors\n\n")
        
        # Atomic coordinates
        f.write("AtomicCoordinatesFormat  Ang\n")
        f.write("%block AtomicCoordinatesAndAtomicSpecies\n")
        symbol_to_species = {sym: i+1 for i, sym in enumerate(unique_symbols)}
        for pos, sym in zip(positions, symbols):
            species_num = symbol_to_species[sym]
            f.write(f"  {pos[0]:16.10f}  {pos[1]:16.10f}  {pos[2]:16.10f}  {species_num}  # {sym}\n")
        f.write("%endblock AtomicCoordinatesAndAtomicSpecies\n\n")
        
        # K-point sampling
        f.write("# K-point sampling\n")
        f.write("kgrid_cutoff       15.0 Ang\n\n")
        
        # DFT parameters
        f.write("# DFT parameters\n")
        f.write("XC.functional      GGA\n")
        f.write("XC.authors         PBE\n")
        f.write("MeshCutoff         300.0 Ry\n")
        f.write("PAO.BasisSize      DZP\n\n")
        
        # SCF options
        f.write("# SCF options\n")
        f.write("MaxSCFIterations   200\n")
        f.write("DM.MixingWeight    0.1\n")
        f.write("DM.NumberPulay     5\n")
        f.write("DM.Tolerance       1.0e-4\n\n")
        
        # Output options
        f.write("# Output options\n")
        f.write("WriteCoorXmol      .true.\n")
        f.write("WriteMDXmol        .true.\n")
        f.write("WriteMDhistory     .true.\n\n")
        
        # Geometry optimization (optional)
        f.write("# Geometry optimization (uncomment to enable)\n")
        f.write("# MD.TypeOfRun     CG\n")
        f.write("# MD.NumCGsteps    100\n")
        f.write("# MD.MaxForceTol   0.04 eV/Ang\n")


def main():
    """Main function to convert CIF to SIESTA format."""
    if len(sys.argv) < 2:
        print("Usage: python cif2siesta.py <input.cif> [output.fdf]")
        print("\nExample:")
        print("  python cif2siesta.py layer_1.cif layer_1.fdf")
        print("  python cif2siesta.py relaxed_structure.cif structure.fdf")
        sys.exit(1)
    
    input_cif = sys.argv[1]
    
    if len(sys.argv) >= 3:
        output_fdf = sys.argv[2]
    else:
        output_fdf = input_cif.replace('.cif', '.fdf')
    
    print(f"\n{'='*60}")
    print("CIF to SIESTA Converter")
    print(f"{'='*60}\n")
    
    print(f"Reading: {input_cif}")
    try:
        atoms = read(input_cif)
        print(f"  Read {len(atoms)} atoms")
        print(f"  Elements: {sorted(set(atoms.get_chemical_symbols()))}")
    except Exception as e:
        print(f"[FAIL] Error reading CIF file: {e}")
        sys.exit(1)
    
    print(f"\nWriting: {output_fdf}")
    try:
        write_siesta_fdf(atoms, output_fdf)
        print(f"  SIESTA input file written")
    except Exception as e:
        print(f"[FAIL] Error writing FDF file: {e}")
        sys.exit(1)
    
    print(f"\n{'='*60}")
    print("Conversion complete!")
    print(f"{'='*60}\n")
    print("Next steps:")
    print("  1. Obtain pseudopotential files (.psf) for each element")
    print("  2. Place them in the same directory or update paths in .fdf")
    print("  3. Run: siesta < {output_fdf} > output.log")
    print()


if __name__ == '__main__':
    main()
